
tasks:
  - name: create virtualenv 
    init: |
      pyenv install 3.8 && 
      pyenv local 3.8 &&
      poetry env use python3.8 &&
      poetry install
      
    command: poetry shell

vscode:
  extensions:
    - gitpod.gitpod-web